# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install pytest coverage

# Command to run tests, e.g. python setup.py test
script:
  - coverage run -m pytest .
  - bash <(curl -s https://codecov.io/bash)
